### ISSUE TITLE
Data Type Missing in Section 4.4 Modelling decisions

### ISSUE THREAD

**Issue by gordonwky** [omltcat/turbulent-flow#10]
I think adding data type to section 4.4 is a good idea since derived variables appeared in the 4.4.4. It may be useful to know the range of these variables and its type (real number or integer or a specific set that satisfied some conditions)

**Comment by omltcat** [comment]
The section is rewritten with https://github.com/omltcat/turbulent-flow/commit/e5e0358501eba787255e66a9734727f3f3dc2265
#45
