### ISSUE TITLE
Consistency of Input

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#13]
1. In section 3.1 system context, it mentions that the inputs would be x, y, z, t but x, y, z are not mentioned elsewhere. Later in section 4.2.1 when talking about the types, it says "(Query) Position of interest $\mathbf{x}$: $\mathbb{R}^3$" I assumed they are talking about the same thing, but it would be better to keep it consistent.
2. The wording "eddy profiles" is mentioned multiple times in the document, by comparing the 3.1 and 4.2.1 I guess it means the number of eddies, eddy length-scale and shape function parameters but I am not sure, it could be stated somewhere explicitly.

**Comment by omltcat** [comment]
Position is always $\mathbf{x}$ now
Eddy profile added with #50
