### ISSUE TITLE
Rationale for constraints

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#14]
In section 4.4.6 the input variable table, the software constraints for $\textbf{x}$* is $-\frac{L_x}{2} \leq \textbf{x}.x \leq \frac{L_x}{2}$, but it is not stated where the $\frac{L_x}{2}$ is from. Also, the choice for typical value could be discussed in Rationale section too.

**Comment by omltcat** [comment]
This is removed as per #39, it's not a software constraint. Should be left to MIS.
