### ISSUE TITLE
Mismatch input of TM:VFF

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#15]
In IM1 $\mathbf{u}'(\mathbf{x},t) = \sqrt{\frac{1}{N}}\sum_{k=1}^{N}\frac{q_\sigma(|\mathbf{r}^k|)}{|\mathbf{r}^k|^3}\mathbf{r}^k\times\alpha^k$ it takes $x$ and $t$ as input and I assume it is using TM:VFF as the equation is same, but in the description of TM1 it takes only a vector as input. And $t$ is actually not used in calculation until $\textbf{x}^k(t)$, which is causing some confusion.

**Comment by omltcat** [comment]
This is just a TM that does not concern with the flow moving yet. I have improved the IM as per #46. It contains everything in forms that they will actually be used. It should be clearer now.
