### ISSUE TITLE
Clarification in IM1

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#16]
1. What is the (s) in the end of $\mathbf{u}'(\mathbf{x},t) = \sqrt{\frac{1}{N}}\sum_{k=1}^{N}\frac{q_\sigma(|\mathbf{r}^k|)}{|\mathbf{r}^k|^3}\mathbf{r}^k\times\alpha^k$ (s), looks like a unit but not sure which one it is referring to.
2. Although mentioned in the symbol table, $\alpha$ should be mentioned again to explain what it is.
3. The $\mathbf{r}^k$ seems like a value but it turns out to be another function, maybe could use something like $\textbf{r}^k(\mathbf{x},t)$ to show it needs further calculation.

**Comment by omltcat** [comment]
1. That was a type lol. Thanks for catching it.
2. Added a dedicated DD to explain $\alpha$ #45 
3. $\mathbf{r}$ is now properly represented as a function #45
