### ISSUE TITLE
Math Symbol/notation

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#17]
Following are some math symbols/notation that I think would be good to add to section 1.4
1. What does the | | mean, the norm of a vector?
2. What is the $\int_{}$ in $\int_{field}\mathbf{u}(\mathbf{x})$?

**Comment by omltcat** [comment]
1. $| |$ is indeed norm of a vector, adding to 1.4
2. That was integration, but I misunderstood what divergence free is. This line has been changed.
