### ISSUE TITLE
Update Repos.csv

### ISSUE THREAD

**Issue by smiths** [omltcat/turbulent-flow#2]
Please create a merge request with your information in Repos.csv.

**Comment by omltcat** [comment]
I updated the repo once again. It should be good to go now.

**Comment by omltcat** [comment]
I saw that it was successfully [merged](https://gitlab.cas.mcmaster.ca/smiths/cas741/-/commit/5cae515319aa22a64dbd854cbab0fdd20cca34f4), thanks.
