### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#22]
There are some math notations or terminologies that I think you assume the readers to understand but I am actually not sure. I am listing them below:
1. In many output fields of section 4, $tol$ is mentioned, but there is no explanation of what it is.
2. What is $std()$ in test-eddy-std, test-field-std-time, test-field-std-intensity. I guess it is the standard derivation?

**Comment by omltcat** [comment]
Yes, std is standard deviation. I will make this more clear.

tol is tolerance. The VnV template puts these parameters at the very end of the document. I should mention this before using them.
