### ISSUE TITLE
Test case derivation explaination

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#24]
In the test case derivation of test-eddy-std, it says "Velocity standard deviation along the eddy orientation should be zero." 
In the test case derivation of test-field-sum, it says "The vector sum of all velocity fluctuations caused by the eddies should be zero."

I guess they are explaining the output, and the output for those two tests are both related to $tol$, but it is not clear how "zero" is related to the output, maybe that could be explained further?

**Comment by omltcat** [comment]
adding explanation
