### ISSUE TITLE
MG+MIS Ready for Review by Dr. Smith

### ISSUE THREAD

**Issue by omltcat** [omltcat/turbulent-flow#31]
Hello Dr. Smith,

Please find the documents here: [MG](https://github.com/omltcat/turbulent-flow/blob/main/docs/Design/SoftArchitecture/MG.pdf), [MIG](https://github.com/omltcat/turbulent-flow/blob/main/docs/Design/SoftDetailedDes/MIS.pdf).

I look forward to your feedback.

Thanks,
Phil

**Comment by smiths** [comment]
[PhilMG.pdf - PDF Expert.pdf](https://github.com/omltcat/turbulent-flow/files/14846236/PhilMG.pdf.-.PDF.Expert.pdf)
[PhilMIS.pdf - PDF Expert.pdf](https://github.com/omltcat/turbulent-flow/files/14846238/PhilMIS.pdf.-.PDF.Expert.pdf)
