### ISSUE TITLE
MG+MIS Ready for Review by Cynthia (Domain Expert) 

### ISSUE THREAD

**Issue by omltcat** [omltcat/turbulent-flow#32]
Hello Cynthia,

Please find the documents here: [MG](https://github.com/omltcat/turbulent-flow/blob/main/docs/Design/SoftArchitecture/MG.pdf), [MIG](https://github.com/omltcat/turbulent-flow/blob/main/docs/Design/SoftDetailedDes/MIS.pdf).

I look forward to your feedback.

Thanks,
Phil

**Comment by CynthiaLiu0805** [comment]
Hi Phil,

The issues are created in #34, #35, #36, #37, #38. Great traceability for pointing back to the SRS :)

Regards,
Cynthia
