### ISSUE TITLE
MG+MIS Ready for Review by Nada (Secondary Reviewer)

### ISSUE THREAD

**Issue by omltcat** [omltcat/turbulent-flow#33]
Hello Nada,

I will assign you this issue once you accept the invitation.

Please find the documents here: [MG](https://github.com/omltcat/turbulent-flow/blob/main/docs/Design/SoftArchitecture/MG.pdf), [MIG](https://github.com/omltcat/turbulent-flow/blob/main/docs/Design/SoftDetailedDes/MIS.pdf).

I look forward to your feedback.

Thanks,
Phil

**Comment by NadaElmasry** [comment]
Hello Phil,
I've provided my feedback in the following issues: #61, #62, #63, #64, #65. 
Overall, the MG and MIS plans are very well-written with great traceability with SRS.
Thank you!
