### ISSUE TITLE
Vector module in MG v.s. type VectorT in MIS

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#36]
In your MG you mention a Vector module, which appears to be an existing ADT that you can utilize directly. However, in your MIS, the type "VectorT" is referenced several times. I guess they are referred to the same thing, but the naming of "VectorT" makes it look like an ADT that you will manually implement.

**Comment by omltcat** [comment]
The message I wanted to convey here is that VectorT is specifically a NumPy array with 3 elements (3D vector), as opposed to the built-in array of python. I will make a list to explain these "T" types.
