### ISSUE TITLE
MG modle classification

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#37]
Given the descriptions:
Software Decision Module: _"Includes data structure and algorithms used in the system that do not provide direct interaction with the user"_ 

If I am understanding correctly, the Main Control Module should not be classified as a software decision module as users use it to interact with the software. The Vector Module should be in the software decision module as it is some pre-defined data structure.

**Comment by omltcat** [comment]
Yes you are correct. I misunderstood these. Adjusting MG and MIS.
