### ISSUE TITLE
Other typos/confusion

### ISSUE THREAD

**Issue by CynthiaLiu0805** [omltcat/turbulent-flow#38]
- Section 6.4.4 the _encode_ function in _out := encode({VectorT})_ is not implemented in local function.
- Do double braces in _{{R+, R+}}_ stands for a 2-d array? Maybe could add this type in the beginning type section.
- Section 8.4.4 exception for _get_vel_ is mentioned in exported access programs but not shown in access routine semantic.

**Comment by omltcat** [comment]
Thanks for the catch
- Adding `encode(response):` to local functions
- {{R+, R+}} is exactly what it shows, an array of 2-element arrays, containing {strength, radius}. I'll add an explanation
- Fixed by #35
