### ISSUE TITLE
SRS Ready For Reviewing by Cynthia (Domain Expert)

### ISSUE THREAD

**Issue by omltcat** [omltcat/turbulent-flow#6]
Hi Cynthia,

I tried my best to make the [SRS document](https://github.com/omltcat/turbulent-flow/blob/main/docs/SRS/SRS.pdf) more understandable, and made a section to explain some of the background information needed to read. If you find any part hard to understand please feel free to point out. 

Thanks,
Phil

**Comment by CynthiaLiu0805** [comment]
Hi Phil,
The review is given by #13 #14 #15 #16 #17. 
Cynthia
