### ISSUE TITLE
MIS: Shape Function Module Clarification

### ISSUE THREAD

**Issue by NadaElmasry** [omltcat/turbulent-flow#62]
In the Access Routine Semantics of the Shape Function Module in "set_active(active_func)", is active_func the name of the shape function? Does set_active() take shape function name as input and internally call one of the squared() or gaussian() functions? It's a bit unclear to me how set_active() works internally.

**Comment by omltcat** [comment]
Because the document is written with python in mind, which allows assigning a variable name to a function. In this case, the "active" variable can point to different functions. By calling "active", you are actually calling the function behind it. I will explain this better in MIS.
