### ISSUE TITLE
SRS review: Question about Eddy shape function

### ISSUE THREAD

**Issue by gordonwky** [omltcat/turbulent-flow#8]
In TM 1, you define eddy shape function with $\sigma_{I}$ and $d^{k}$, while in IM 1, you mention $L_x,L_y$ etc and other parameter in eddy shape function are the input for the flow construction. Therefore, I am confused that is  $L_x,L_y$ etc. parameter for eddy shape function. And what is the role of eddy shape function in IM 1 or how is it relate to these parameter?

**Comment by omltcat** [comment]
$L_x,L_y,L_z$ are is the size of the entire flow field, not directly related to shape function. But you are right about IM1, shape function is already referred TM2, so no need to put it in IM1.

**Comment by omltcat** [comment]
IM1 reference fixed in [5795814](https://github.com/omltcat/turbulent-flow/commit/5795814c47f0741090570ef50690cc89afcf5c48)
