### ISSUE TITLE
JOSS paper complete draft review

### ISSUE THREAD

**Issue by omltcat** [omltcat/turbulent-flow#81]
@smiths I have the [complete document](https://github.com/omltcat/turbulent-flow/blob/main/paper/paper.md) ready with all metadata, figures and citations. Would you mind take a look? Thanks. We can discuss it over today's meeting. (We do have a meeting today right?)

**Comment by smiths** [comment]
Yes, we do have a meeting at the normal time on Teams.  I'll do my best to review before the meeting.

**Comment by smiths** [comment]
Feedback as I quickly review the paper:

- we should make Dr. Lightstone, Dr. Tullis and Nikita co-authors.  If they don't feel that they are contributing, they can have the option to remove their names
- change "they are often deemed too computationally expensive and see limited use in practice." to "they are often deemed too computationally expensive and thus see limited use in practice."
- when all acronyms, such as IC and BC, are introduced capitalize the letters that are used in the acronym.  For instance, it should be "... generating Initial Conditions (IC) and Boundary Conditions (BC) ..."
- at the end of the first paragraph it should be "the Synthetic Eddy Method".
- start second paragraph with `SynthEddy` has the potential ...
- great to include references
- for DNS another option to saying prior simulations is to mention that a larger flow field needs to be simulated to provide an opportunity for the turbulent flow to develop
- are there any references from Nikita that you can cite?
- "It models turbulent flow fields consists" should be "It models turbulent flow fields consisting"
- "User can generate turbulent flow and query velocity field to" to "The user can generate turbulent flow and query the velocity field to"
- Do any of the inputs have units?  I feel like they don't.
- Pointer to more detailed directions for customization?
- mistake with "the user can query a keep querying a thin subsection"
- Nice to have text between all headings
- provide a pointer to getting started information
