### ISSUE TITLE
SRS Review Characteristics of Intended Reader - Definition on basic understanding

### ISSUE THREAD

**Issue by gordonwky** [omltcat/turbulent-flow#9]
The basic understanding of fluid theories and CFD could be more specific here. For example, what kind of terminology the reader should know? What kind of basic understanding is required ,  in undergraduate level or graduate level ?

**Comment by omltcat** [comment]
More specific definition added in [510f8a9](https://github.com/omltcat/turbulent-flow/commit/510f8a95ad419b7bb3d8fa426c4a4915d300d1de)
